### ISSUE TITLE
StackHorizontal fails to compile in Unity 6000.6.2f1 (UxmlFactory / UxmlTraits)

### ISSUE THREAD

**Issue by aehomay** [OpenCommissioning/OC_Unity_Core#139]
## Environment
- Unity 6000.6.2f1 on Windows.
- Open Commissioning 1.3.16 installed from `upm` (package cache revision `83e16e5d4f74`).
- The same unguarded declarations are present in local master `be33192` and development `e040856`.

## Reproduction
1. Create a Unity 6000.6.2f1 project.
2. Install NaughtyAttributes and UniTask as described in the README.
3. Install `https://github.com/OpenCommissioning/OC_Unity_Core.git#upm`.
4. Wait for script compilation.

## Actual result
The console reports these errors in `Runtime/Scripts/VisualElements/StackHorizontal.cs`:

```text
(8,40): error CS0308: The non-generic type 'StackHorizontal.UxmlFactory' cannot be used with type arguments
(9,53): error CS0426: The type name 'UxmlTraits' does not exist in the type 'VisualElement'
```

Compilation fails, preventing normal use of the package's editor extensions.

## Expected result
The package compiles and StackHorizontal remains usable from C# and UXML, while preserving Unity 2022.3 support.

## Proposed fix
Follow the `UNITY_6000_3_OR_NEWER` guard already used by the editor controls: use `[UxmlElement]` and a partial class on that path, and retain the existing factory/traits declarations on older versions. Preserve the `OC.VisualElements.StackHorizontal` UXML name and existing constructor/Add behavior. No minimum-version or package-version change is needed.

This report concerns this specific compilation failure, not a claim that all Unity 6 releases lack the legacy API or that the whole package has been validated on every Unity version.

Reference: https://docs.unity3d.com/6000.0/Documentation/ScriptReference/UIElements.UxmlElementAttribute.html
